// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PPaJtkzr6K63J59g8nLVoYG9oUgrSxU',
    appId: '1:948508900116:android:876daaec51f29e9b56a001',
    messagingSenderId: '948508900116',
    projectId: 'no-ghost',
    storageBucket: 'no-ghost.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EjlUaAa-77m6beEFDlCgRXi99tjrC28',
    appId: '1:948508900116:ios:f0e5beb8077f7e6356a001',
    messagingSenderId: '948508900116',
    projectId: 'no-ghost',
    storageBucket: 'no-ghost.firebasestorage.app',
    iosClientId: '948508900116-hvuv98ooig4bfme2i5p286grba3dn5ag.apps.googleusercontent.com',
    iosBundleId: 'com.noghost.dating.noGhost',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh3npV5coptOEEfJeziAwrIjGMY3hsBzk',
    appId: '1:948508900116:web:3213e2dacacfb4e956a001',
    messagingSenderId: '948508900116',
    projectId: 'no-ghost',
    authDomain: 'no-ghost.firebaseapp.com',
    storageBucket: 'no-ghost.firebasestorage.app',
    measurementId: 'G-6LKKFCZL2J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-EjlUaAa-77m6beEFDlCgRXi99tjrC28',
    appId: '1:948508900116:ios:f0e5beb8077f7e6356a001',
    messagingSenderId: '948508900116',
    projectId: 'no-ghost',
    storageBucket: 'no-ghost.firebasestorage.app',
    iosClientId: '948508900116-hvuv98ooig4bfme2i5p286grba3dn5ag.apps.googleusercontent.com',
    iosBundleId: 'com.noghost.dating.noGhost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh3npV5coptOEEfJeziAwrIjGMY3hsBzk',
    appId: '1:948508900116:web:d505c0fb668c87f756a001',
    messagingSenderId: '948508900116',
    projectId: 'no-ghost',
    authDomain: 'no-ghost.firebaseapp.com',
    storageBucket: 'no-ghost.firebasestorage.app',
    measurementId: 'G-Q8WJWLXP9X',
  );

}